/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var ChecktypeError = kurentoClient.checkType.ChecktypeError;

var Filter = kurentoClient.register.abstracts.Filter;


/**
 * Create an element
 *
 * @classdesc
 *  This filter detects DTMF tones in an audio stream. When a DTMF tone is found
 *
 * @extends module:core/abstracts.Filter
 *
 * @constructor module:dtmfdetect.DtmfDetect
 *
 * @fires {@link module:dtmfdetect#event:DtmfDetected DtmfDetected}
 */
function DtmfDetect(){
  DtmfDetect.super_.call(this);
};
inherits(DtmfDetect, Filter);


/**
 * @alias module:dtmfdetect.DtmfDetect.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link module:core.MediaPipeline MediaPipeline}
 */
DtmfDetect.constructorParams = {
  mediaPipeline: {
    type: 'kurento.MediaPipeline',
    required: true
  }
};

/**
 * @alias module:dtmfdetect.DtmfDetect.events
 *
 * @extends module:core/abstracts.Filter.events
 */
DtmfDetect.events = Filter.events.concat(['DtmfDetected']);


/**
 * Checker for {@link module:dtmfdetect.DtmfDetect}
 *
 * @memberof module:dtmfdetect
 *
 * @param {external:String} key
 * @param {module:dtmfdetect.DtmfDetect} value
 */
function checkDtmfDetect(key, value)
{
  if(!(value instanceof DtmfDetect))
    throw ChecktypeError(key, DtmfDetect, value);
};


module.exports = DtmfDetect;

DtmfDetect.check = checkDtmfDetect;
